#!/usr/bin/env node
// Pulls the latest changes, reinstalls dependencies, and applies any new database
// migrations. Never force-pushes or discards local work — if the working tree is dirty
// or history has diverged, it stops and tells you what to do instead of guessing.
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { captureOutput, commandExists, run, section, step, warn } from "./lib.mjs";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));

section("Pulling latest changes");
if (!commandExists("git --version") || !existsSync(join(rootDir, ".git"))) {
  warn("Not a git checkout (or git isn't installed) — skipping pull.");
} else {
  const dirty = captureOutput("git status --porcelain", { cwd: rootDir });
  // A modified package-lock.json is the one kind of "uncommitted change" that's always
  // safe to discard here: it's fully regenerated by `npm install` a few lines down
  // regardless, and differs machine-to-machine easily (a different npm version, a
  // different OS's platform-specific optional dependencies) even when package.json
  // hasn't changed at all — the exact situation that kept blocking pulls on a Linux
  // deployment box after `npm install` had run there. Anything else dirty still aborts.
  // Porcelain format is a 2-char status code + a space + the path, per line.
  const dirtyFiles = dirty ? dirty.split("\n").map((line) => line.slice(3).trim()) : [];
  const onlyLockfile = dirtyFiles.length === 1 && dirtyFiles[0] === "package-lock.json";

  if (dirty && !onlyLockfile) {
    warn("Working tree has uncommitted changes — skipping pull so nothing gets overwritten.");
    warn("Commit or stash your changes, then re-run this script.");
  } else {
    if (onlyLockfile) {
      step("Only package-lock.json is locally modified (npm install regenerates it below anyway) — discarding it before pulling.");
      run("git checkout -- package-lock.json", { cwd: rootDir });
    }
    const before = captureOutput("git rev-parse HEAD", { cwd: rootDir });
    if (run("git pull --ff-only", { cwd: rootDir, optional: true })) {
      const after = captureOutput("git rev-parse HEAD", { cwd: rootDir });
      if (before && after && before !== after) {
        step("New commits:");
        run(`git log --oneline ${before}..${after}`, { cwd: rootDir, optional: true });
      } else {
        step("Already up to date.");
      }
    } else {
      warn("`git pull --ff-only` failed — your branch has probably diverged from its remote.");
      warn("Resolve that manually (e.g. `git pull` or `git rebase`), then re-run this script.");
    }
  }
}

section("Installing dependencies");
run("npm install", { cwd: rootDir });

section("Applying database migrations");
if (!existsSync(join(rootDir, "server", ".env"))) {
  warn("server/.env doesn't exist yet — run `npm run setup` first.");
} else if (!run("npm run db:deploy --workspace=server", { cwd: rootDir, optional: true })) {
  // Non-fatal: this machine might only be running the app (e.g. against a deployed
  // server) with no reason to have the local dev Postgres up right now — don't block
  // `npm install` / the rest of the update over a database this run may not even need.
  warn("Couldn't apply migrations — is the local dev Postgres running? (`docker compose up -d`)");
  warn("Harmless if you're not using the local dev server right now; otherwise start Postgres and re-run this.");
} else if (!run("npm run db:generate --workspace=server", { cwd: rootDir, optional: true })) {
  warn("Prisma client generation failed (often a stale lock from another running process) — re-run `npm run db:generate --workspace=server` if types look out of date.");
}

section("Done");
console.log("Restart `npm run dev:server` / `npm run dev:app` to pick up the changes.");
